config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "short_urls#new"
  resources :short_urls, only: [:index, :create, :new, :show]
  get '/:short_url', to: "short_urls#redirect", as: :shorten
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/short_url.rb
require 'uri'

class ShortUrl < ApplicationRecord
  
  validates_presence_of :original_url
  validates :original_url, format: URI::regexp(%w[http https])
  
  validates_length_of :original_url, in: 3..255

  before_create :generate_short_url, :sanitize
  
  def generate_short_url
    @slugs ||= self.class.pluck(:slug)
    uri = URI(original_url)
    initials = uri.host.split('.')[-2]
    slug_string = initials.first + initials.last
    slug_string += SecureRandom.urlsafe_base64(3)
    generate_short_url if @slugs.include?(slug_string)
    self.slug = slug_string
  end

  def sanitize
    original_url.strip!
    sanitize_url = self.original_url.downcase.gsub(/(https?:\/\/)|(www\.)/,"")
    self.original_url = "http://#{sanitize_url}"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController

  before_action :set_url, only: [:show, :redirect]

  def index
    @urls = ShortUrl.all.order(click_count: :desc, updated_at: :desc).first(100)
  end

  def new
    @url = ShortUrl.new
  end
  
  def create
    @url = ShortUrl.find_or_initialize_by(short_url_params)
    if @url.save
      redirect_to short_url_path(@url.slug)
    else
      flash[:error] = @url.errors.full_messages
      redirect_to new_short_url_path
    end
  end
  
  def redirect
    @url.update(click_count: @url.click_count + 1)
    redirect_to @url.sanitize
  end

  def show
  end
  
  private
    def short_url_params
      params.require(:short_url).permit(:original_url)
    end

    def set_url
      @url = ShortUrl.find_by(slug: params[:short_url] || params[:id])
      render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found unless @url
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/short_urls_helper.rb
module ShortUrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShortenerUrl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Home", short_urls_path()%>
    <%= link_to "New", new_short_url_path()%>
    <%= yield %>
  </body>
</html>

app/views/short_urls/index.html.erb
<table style="width:100%">
  <tr>
    <th>Title</th>
    <th>Original Url</th>
    <th>Slug</th>
    <th>Clicked</th>
  </tr>
  <% @urls.each do |url| %>
    <tr>
      <td><%= url.title%></td>
      <td><%= url.original_url%></td>
      <td><%= link_to "#{request.base_url}#{shorten_path(short_url: url.slug)}", shorten_path(short_url: url.slug)%></td>
      <td><%= url.click_count%></td>
    </tr>
  <% end %>
</table>

app/views/short_urls/new.html.erb
<%= flash[:error] %>
<%= form_with model: @url do |form| %>
  <p>Please input long url: <%= form.text_field :original_url %></p>
  <%= form.submit %>
<% end %>

app/views/short_urls/show.html.erb
<table style="width:100%">
  <tr>
    <th>Title</th>
    <th>Original Url</th>
    <th>Slug</th>
    <th>Clicked</th>
  </tr>
  <tr>
    <td><%= @url.title%></td>
    <td><%= @url.original_url%></td>
    <td><%= link_to "#{request.base_url}#{shorten_path(short_url: @url.slug)}", shorten_path(short_url: @url.slug)%></td>
    <td><%= @url.click_count%></td>
  </tr>

</table>